language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - node
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  edge: true
  skip-cleanup : true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on:
<<<<<<< HEAD
    branch: master
=======
    branch: master
>>>>>>> 577540e09f0ad7b0c48b5cce2147cbc96578446c
